#!/usr/bin/env php
<?php

define('WEB', dirname(__DIR__, 1) . '/');

if (PHP_SAPI!='cli') {
    exit('O utilitario Nano nao pode ser acessado diretamente' . PHP_EOL);
}

# Config & Helpers
include WEB . 'app/config.php';
include APP . 'functions/helpers.php';

$cmd = isset($argv[1]) ? $argv[1] : null;
$arg = isset($argv[2]) ? $argv[2] : null;
$opt = isset($argv[3]) ? $argv[3] : null;

if (is_null($cmd)) {
    cli("\e[1mNano:\e[0m inclua 'cmds' para ver os comandos");
    return;
}

if ($cmd=='cmds') {
	cli('Comandos:');
	cli("mig create: \033[32m" . 'Cria uma nova migration' . "\033[0m");
	cli("mig up [n]: \033[32m" . 'Avança as migrations, aceita limite $n' . "\033[0m");
	cli("mig down [n]: \033[32m" . 'Reverte as migrations, aceita limite $n' . "\033[0m");
	return;
}

if (!is_file(WEB . 'vendor/autoload.php')) {
	cli('Instale o composer.');
	return;
}

# Autoload & migrations
include WEB . 'vendor/autoload.php';
include APP . 'functions/migrations.php';

if ($cmd=='mig') {
    if ($arg=='create') {
        if (empty($opt)) {
            cli('Este comando requer um nome para identificação.');
            return;
        }
        if ($mig_name = create($opt)) {
            cli("\033[32mMigration $mig_name criada com sucesso.\033[0m");
            return;
        }
        cli("\033[33mAlgum erro ao criar migration.\033[0m");
        return;
    }

    if ($arg=='down') {
        down($opt);
        return;
    }

    if ($arg=='up' or empty($arg)) {
        up($opt);
        return;
    }
    cli('Opção "'. $arg . '" desconhecida.');
    return;
}

# DB Update
if ($cmd=='update-db') {
    if (!is_file(__DIR__ . '/.env')) {
        exit('Configure o arquivo app/.env a partir de app/.env.lock' . PHP_EOL);
    }

    $env = parse_ini_file(__DIR__ . '/.env');

    if (empty($env['PROD_DB_HOST']) OR empty($env['PROD_DB_USER']) OR empty($env['PROD_DB_PASS']) || empty($env['PROD_DB_NAME'])) {
        exit('Configure as crendencias de produção em app/.env' . PHP_EOL);
    }

    $dumpFile = APP . 'tmp/mock.sql';

    $dumpCmd = sprintf(
        'mariadb-dump --ssl=0 -h%s -u%s -p%s %s > %s',
        escapeshellarg($env['PROD_DB_HOST']),
        escapeshellarg($env['PROD_DB_USER']),
        escapeshellarg($env['PROD_DB_PASS']),
        escapeshellarg($env['PROD_DB_NAME']),
        escapeshellarg($dumpFile)
    );

    cli('📦 Exportando produção...');
    exec($dumpCmd, $out, $ret);

    if ($ret !== 0) {
        exit('Erro ao exportar banco de produção' . PHP_EOL);
    }

    $importCmd = sprintf(
        'mysql -h%s -u%s -p%s %s < %s',
        escapeshellarg(DB_HOST),
        escapeshellarg(DB_USER),
        escapeshellarg(DB_PASS),
        escapeshellarg(DB_NAME),
        escapeshellarg($dumpFile)
    );

    cli('📥 Importando para banco local...');
    exec($importCmd, $out, $ret);

    if ($ret !== 0) {
        exit('Erro ao importar banco local');
    }

    cli('✅ Mock local criado com sucesso!');
    return;
}

cli('Comando "'. $cmd . '" não encontrado.');
